apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: saleor-api-hpa
  namespace: saleor-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: saleor-api
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: saleor-dashboard-hpa
  namespace: saleor-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: saleor-dashboard
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70