apiVersion: apps/v1
kind: Deployment
metadata:
  name: saleor-worker
  namespace: saleor-dev
  labels:
    app: saleor-worker
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saleor-worker
  template:
    metadata:
      labels:
        app: saleor-worker
        environment: dev
    spec:
      containers:
      - name: saleor-worker
        image: ghcr.io/saleor/saleor:3.15
        command: ["celery"]
        args: ["-A", "saleor", "worker", "--loglevel=info", "--without-gossip"]
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: saleor-secrets
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: saleor-secrets
              key: REDIS_URL
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: saleor-secrets
              key: SECRET_KEY
        - name: DEFAULT_CHANNEL_SLUG
          valueFrom:
            configMapKeyRef:
              name: saleor-config
              key: DEFAULT_CHANNEL_SLUG
        - name: DEFAULT_FROM_EMAIL
          valueFrom:
            configMapKeyRef:
              name: saleor-config
              key: DEFAULT_FROM_EMAIL
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        volumeMounts:
        - name: media-storage
          mountPath: /app/media
      volumes:
      - name: media-storage
        emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: saleor-beat
  namespace: saleor-dev
  labels:
    app: saleor-beat
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saleor-beat
  template:
    metadata:
      labels:
        app: saleor-beat
        environment: dev
    spec:
      containers:
      - name: saleor-beat
        image: ghcr.io/saleor/saleor:3.15
        command: ["celery"]
        args: ["-A", "saleor", "beat", "--loglevel=info"]
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: saleor-secrets
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: saleor-secrets
              key: REDIS_URL
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: saleor-secrets
              key: SECRET_KEY
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"