apiVersion: apps/v1
kind: Deployment
metadata:
  name: saleor-storefront
  namespace: saleor-dev
  labels:
    app: saleor-storefront
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saleor-storefront
  template:
    metadata:
      labels:
        app: saleor-storefront
        environment: dev
    spec:
      containers:
      - name: saleor-storefront
        image: nginx:alpine
        ports:
        - containerPort: 80
        env:
        - name: NEXT_PUBLIC_API_URI
          value: "http://storefront-dev.aksa.ai/graphql/"
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: saleor-storefront
  namespace: saleor-dev
  labels:
    app: saleor-storefront
spec:
  selector:
    app: saleor-storefront
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
