apiVersion: apps/v1
kind: Deployment
metadata:
  name: saleor-chat-service-v2-1-0
  namespace: default
  labels:
    app: saleor-chat-service
    version: v2.1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saleor-chat-service
      version: v2.1.0
  template:
    metadata:
      labels:
        app: saleor-chat-service
        version: v2.1.0
    spec:
      containers:
      - name: saleor-chat-service
        image: saleor-chat-service:v2.1.0
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "development"
        - name: PORT
          value: "3001"
        - name: GEMINI_API_KEY
          value: "YOUR_GEMINI_API_KEY"
        - name: REDIS_URL
          value: "redis://redis:6379"
        - name: SALEOR_API_URL
          value: "http://api:8000/graphql/"
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: saleor-chat-service-v2-1-0
  namespace: default
spec:
  selector:
    app: saleor-chat-service
    version: v2.1.0
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
  type: ClusterIP