apiVersion: v1
kind: Secret
metadata:
  name: saleor-secrets  
  namespace: saleor-dev
type: Opaque
data:
  # Base64 encoded values - these should be replaced with actual values
  SECRET_KEY: Y2hhbmdlbWUtZGV2LXNlY3JldC1rZXk=  # changeme-dev-secret-key
  DATABASE_URL: cG9zdGdyZXM6Ly9zYWxlb3I6c2FsZW9yQGRiL3NhbGVvcg==  # Will be updated by deployment
  REDIS_URL: cmVkaXM6Ly9yZWRpczoyNzAxNy8x  # Will be updated by deployment
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudsql-secret
  namespace: saleor-dev
type: Opaque
data:
  # These will be populated by the deployment script from Secret Manager
  username: c2FsZW9y  # saleor
  password: ""  # Will be filled by deployment script